name: 'Cherry-pick PR'
description: 'Cherry-pick the PR'
author: '134130'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-pull-request'
  color: 'red'

# Define your inputs here.
inputs:
  pr:
    description: 'The PR number which you want to cherry-pick'
    required: true
  onto:
    description: 'The target branch which you want to base on'
    required: true
  token:
    description: 'The GitHub token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
